namespace Nexus.Core.Orchestrator;

public sealed class StubCoordinator : ICoordinator
{
    // Returns a canned 2-task decomposition: auth (no deps) and booking (depends on auth).
    public Task<IReadOnlyList<SubTask>> DecomposeAsync(string instruction, CancellationToken ct)
    {
        var tasks = new List<SubTask>
        {
            new("auth", instruction, new[] { "src/auth/**" }, Array.Empty<string>()),
            new("booking", instruction, new[] { "src/booking/**" }, new[] { "auth" })
        };
        return Task.FromResult<IReadOnlyList<SubTask>>(tasks);
    }

    // Returns fake Java interface + JUnit test so the full pipeline runs offline.
    public Task<ContractGenerationResult> GenerateContractAsync(SubTask subTask, CancellationToken ct)
    {
        var pascal = ToPascal(subTask.ModuleName);
        var pkg = $"com.example.{subTask.ModuleName.Replace("-", "")}";
        var pkgPath = pkg.Replace('.', '/');

        var result = new ContractGenerationResult(
            subTask.ModuleName,
            $"src/main/java/{pkgPath}/I{pascal}Service.java",
            $"package {pkg};\n\n" +
            $"/** Stub interface generated by NEXUS (offline mode). */\n" +
            $"public interface I{pascal}Service {{\n" +
            $"    /** Executes the primary operation. */\n" +
            $"    boolean execute(String input);\n" +
            $"}}\n",
            $"src/test/java/{pkgPath}/{pascal}ServiceTest.java",
            $"package {pkg};\n\n" +
            $"import org.junit.jupiter.api.Test;\n" +
            $"import static org.junit.jupiter.api.Assertions.*;\n\n" +
            $"class {pascal}ServiceTest {{\n" +
            $"    @Test\n" +
            $"    void execute_withValidInput_returnsTrue() {{\n" +
            $"        I{pascal}Service sut = input -> true;\n" +
            $"        assertTrue(sut.execute(\"test\"));\n" +
            $"    }}\n" +
            $"}}\n");

        return Task.FromResult(result);
    }

    private static string ToPascal(string kebab) =>
        string.Concat(kebab.Split('-').Select(w => char.ToUpperInvariant(w[0]) + w[1..]));
}

public record SubTask(string ModuleName, string Instruction, string[] OwnsFiles, string[] DependsOn);
